### ISSUE TITLE
Convert png images

### ISSUE THREAD

**Issue by tappi287** [tappi287/RenderKnecht#6]
knecht_deltagen ERROR: Rendered image could not be verified as valid image file after 180 seconds.

Traceback (most recent call last):
  File "modules\knecht_deltagen.py", line 53, in create_png_images
  File "site-packages\imageio\core\functions.py", line 206, in imread
  File "site-packages\imageio\core\functions.py", line 129, in get_reader
  File "site-packages\imageio\core\format.py", line 168, in get_reader
  File "site-packages\imageio\core\format.py", line 217, in __init__
  File "site-packages\imageio\plugins\freeimage.py", line 85, in _open
  File "site-packages\imageio\plugins\_freeimage.py", line 846, in load_from_filename
ValueError: Could not load bitmap "...hdr": RGBE read error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "modules\knecht_deltagen.py", line 762, in send_variants
  File "modules\knecht_deltagen.py", line 973, in render_loop
  File "modules\knecht_deltagen.py", line 57, in create_png_images
TypeError: must be str, not ValueError

**Comment by tappi287** [comment]
Bug fixed, exception handled as str. Verify image timeout increased to 3300secs/55mins
